feat: add more linting rules and husky hooks

diff --git a/.husky/post-merge b/.husky/post-merge
--- a/.husky/post-merge
+++ b/.husky/post-merge
@@ -3,11 +3,32 @@
 
 changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"
 
-check_run() {
-	echo "$changed_files" | grep --quiet "$1" && eval "$2"
-}
+echo "..."
 
-if check_run package.json; then 
-  echo "Running yarn install"
-  "yarn install"
-if
+#  function  to check package.json and yarn.lock file changes
+check_package_json_and_yarn_lock() {
+  echo "🕵️📦 Checking package file changes..."
+  if [ -n "$changed_files" ]; then
+    if [ -n "$(echo "$changed_files" | grep package.json)" ]; then
+      echo "📦 package.json file changed"
+      yarn install
+    fi
+    if [ -n "$(echo "$changed_files" | grep yarn.lock)" ]; then
+      echo "📦 yarn.lock file changed"
+      yarn install
+    fi
+  fi
+}
+  
+if [ -z "$changed_files" ]; then
+  echo "🤷‍♂️ No files changed"
+  exit 0
+fi
+
+# run check_package_json_and_yarn_lock function 
+check_package_json_and_yarn_lock || (
+  echo "❌ changes in packages checks failed"
+  exit 1
+)
+
+echo "✅ No package or yarn.lock file changes found"
diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,9 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-yarn pre-commit
+yarn pre-commit || (
+  echo "❌ Pre-commit checks failed"
+  exit 1
+)
+
+echo '✅ Pre-commit checks passed!'
